version: "3.8"

services:
  web:
    build:
      context: .
      target: base
    image: branchpage:latest
    container_name: branchpage_web
    command: mix phx.server
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - .:/branchpage

  db:
    image: postgres:13
    container_name: branchpage_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGUSER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
