name: Update dev image

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: felipelincoln
          password: ${{ secrets.WRITE_PACKAGE_TOKEN }}

      - name: Docker push
        run: |
          docker pull docker.pkg.github.com/felipelincoln/branchpage/dev:latest
          docker build --tag docker.pkg.github.com/felipelincoln/branchpage/dev:latest --cache-from docker.pkg.github.com/felipelincoln/branchpage/dev:latest .
          docker push docker.pkg.github.com/felipelincoln/branchpage/dev:latest
